apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: devgate-showcase-test
  title: Devgate Showcase Test
  description: |
    This is the Showcase of Devgate of kubernetes plugin
  links:
    - title: Infineon
      url: https://www.infineon.com/
    - title: Infineon Devspace
      url: https://devspaces.eu-at-3.icp.infineon.com/dashboard/#/create-workspace?tab=quick-add
    - title: Devgate console
      url: https://devgate.eu-de-1.icp.infineon.com/
  annotations:
    backstage.io/kubernetes-id: 'operation-first'
spec:
  type: website
  system: devgate
  owner: devgate
  lifecycle: production
  dependsOn:
    - resource:pgdb
    - resource:argocd
    - resource:obc
    - resource:keycloak
    - resource:github
